### ISSUE TITLE
Running in a docker container

### ISSUE THREAD

**Issue by damiendawreck** [gabrielcsapo/node-git-server#65]
I am trying to run the git server in a docker container running on a ubuntu image with nodejs 12 installed. It starts fine, but whenever I try and push/pull etc. It gives me the following error

```
server running at port 7000
events.js:200
throw er; // Unhandled 'error' event
^
Error: spawn git ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:81:21) {
errno: 'ENOENT',
code: 'ENOENT',
syscall: 'spawn git',
path: 'git',
spawnargs: [ 'init', '--bare', '/repos/test.git' ]
}
```

My code is just the base example for running a server

```
const path = require('path');
const Server = require('node-git-server');
const serverPort = process.env.SERVERPORT || 7000;

const repos = new Server(path.resolve(__dirname, '../repos'), {
    autoCreate: true
});

repos.on('push', (push) => {
    console.log(`push ${push.repo}/${push.commit} (${push.branch})`);
    push.accept();
});

repos.on('fetch', (fetch) => {
    console.log(`fetch ${fetch.commit}`);
    fetch.accept();
});

repos.on('pull', (pull) => {
    console.log(`pull ${pull}`);
    pull.accept();
});

repos.listen(serverPort, () => {
    console.log(`server running at port ${serverPort}`);
});
```

I would think it has to do with the autoCreate but I'm not sure.

**Comment by damiendawreck** [comment]
I had not installed git on the docker image yet
