### ISSUE TITLE
Three tests are failing

### ISSUE THREAD

**Issue by mattwynne** [gabrielcsapo/node-git-server#81]
Hi,

First of all, thanks for this fantastic little library. We're using it to help us build https://github.com/smartbear/git-en-boite and it's been invaluable to help us isolate our tests. ❤️

I have a contribution I want to make, so I cloned the repo and ran the tests. I get three failures:

```
$ npm run coverage

> node-git-server@0.6.1 coverage /Users/matt/projects/node-git-server
> tap test/*.js --coverage --coverage-report=lcov

test/git.js .....push doom.git/bc8d72f90b0c25e2b67c3520382b8c57bf4fee4c
....push doom.git/bc8d72f90b0c25e2b67c3520382b8c57bf4fee4c
test/git.js ....................................... 117/120
  not ok should be equal
    operator: equal
    expected: >-
      'Cloning into \'doom.git doom1\'...\nfatal: unable to access
      \'http://root:world@localhost:14954/doom.git doom1/\': Empty reply from
      server\n'
    actual: >-
      'Cloning into \'doom.git doom1\'...\nfatal: unable to access
      \'http://localhost:14954/doom.git doom1/\': The requested URL returned error:
      400\n'
    at: >-
      ChildProcess.<anonymous>
      (/Users/matt/projects/node-git-server/test/git.js:690:13)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:80:32)
          at Test.equal (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:389:10)
          at Test.bound [as equal] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:80:32)
          at ChildProcess.<anonymous> (/Users/matt/projects/node-git-server/test/git.js:690:13)
          at ChildProcess.emit (events.js:314:20)
          at ChildProcess.EventEmitter.emit (domain.js:483:12)
          at maybeClose (internal/child_process.js:1022:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

  not ok should be equal
    operator: equal
    expected: >-
      'Cloning into \'doom.git doom1\'...\nfatal: unable to access
      \'http://root:world@localhost:51805/doom.git doom1/\': Empty reply from
      server\n'
    actual: >-
      'Cloning into \'doom.git doom1\'...\nfatal: unable to access
      \'http://localhost:51805/doom.git doom1/\': The requested URL returned error:
      400\n'
    at: >-
      ChildProcess.<anonymous>
      (/Users/matt/projects/node-git-server/test/git.js:760:13)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:80:32)
          at Test.equal (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:389:10)
          at Test.bound [as equal] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:80:32)
          at ChildProcess.<anonymous> (/Users/matt/projects/node-git-server/test/git.js:760:13)
          at ChildProcess.emit (events.js:314:20)
          at ChildProcess.EventEmitter.emit (domain.js:483:12)
          at maybeClose (internal/child_process.js:1022:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

  not ok should be equal
    operator: equal
    expected: >-
      'Cloning into \'doom.git doom1\'...\nfatal: unable to access
      \'http://root:world@localhost:46243/doom.git doom1/\': Empty reply from
      server\n'
    actual: >-
      'Cloning into \'doom.git doom1\'...\nfatal: unable to access
      \'http://localhost:46243/doom.git doom1/\': The requested URL returned error:
      400\n'
    at: >-
      ChildProcess.<anonymous>
      (/Users/matt/projects/node-git-server/test/git.js:824:13)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:80:32)
          at Test.equal (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:389:10)
          at Test.bound [as equal] (/Users/matt/projects/node-git-server/node_modules/tape/lib/test.js:80:32)
          at ChildProcess.<anonymous> (/Users/matt/projects/node-git-server/test/git.js:824:13)
          at ChildProcess.emit (events.js:314:20)
          at ChildProcess.EventEmitter.emit (domain.js:483:12)
          at maybeClose (internal/child_process.js:1022:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

test/http-duplex.js POST /
GET /
GET /info
test/http-duplex.js ................................... 3/3 1s
test/util.js .......................................... 9/9
total ............................................. 129/132


  129 passing (10s)
  3 failing
```

Is this expected? From what I can tell, the [travis build](https://travis-ci.org/github/gabrielcsapo/node-git-server) seems to be failling in a similar way. Perhaps the expected output just needs to be updated?

I know how hard it can be to keep projects like this up to date, but I have some time and energy to help so let me know and maybe I can help fix things.

**Comment by gabrielcsapo** [comment]
Hello @mattwynne i will work on unblocking this, this weekend!

**Comment by gabrielcsapo** [comment]
fixed via https://github.com/gabrielcsapo/node-git-server/commit/34b3b8bebb50f240b7217e4cec6423a07a355c35
