### ISSUE TITLE
TypeError: next is not a function

### ISSUE THREAD

**Issue by milesconrad** [gabrielcsapo/node-git-server#91]
When I run the authentication sample code from the [documentation](https://gabrielcsapo.github.io/node-git-server/code/index.html) and then try to clone an existing repository, I get the following error. I've changed nothing about the sample code other than the directory and the port number, so I'd assume this is an issue with the source code.

> server.js:13
>         next();
>         ^
> 
> TypeError: next is not a function
>     at Git.authenticate (server.js:13:9)
>     at Git.res.statusCode (node_modules/node-git-server/lib/git.js:307:38)
>     at next (node_modules/node-git-server/lib/git.js:425:32)
>     at Git.handle (node_modules/node-git-server/lib/git.js:427:9)
>     at Server.<anonymous> (node_modules/node-git-server/lib/git.js:450:16)
>     at Server.emit (node:events:390:28)
>     at parserOnIncoming (node:_http_server:951:12)
>     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> 
> Node.js v17.2.0

**Comment by milesconrad** [comment]
Is there any update on this? I'd love to set up a repository with a password and this is the closest thing I can find to it.
